# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
  login_listener:
    # path of the previously created class
    class:  AppBundle\EventListener\LoginListener
    arguments:
      $em: "@doctrine.orm.entity_manager"
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

  app.form.handler.registration:
    class: AppBundle\Form\RegistrationFormHandler
    arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
    scope: request
