<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * WishlistItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistItemRepository extends EntityRepository
{
    public function getByUserOrSessId(User $user = null, $sessId, $product = null)
    {
        $params = [];
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb
            ->select('i,w')
            ->from('AppBundle:WishlistItem','i')
            ->innerJoin('i.wishlist','w')
        ;



        if($user){
            $qb->where('w.user = :user');
            $params['user'] = $user;
        }elseif($sessId){
            $qb->where('w.sessId = :sessId');
            $params['sessId'] =  $sessId;
        }else{
            return null;
        }

        if(!is_null($product)){
            $qb->andWhere('i.product = :product');
            $params['product'] = $product;
        }

        $qb->setParameters($params);

        try{
            //echo $qb->getQuery()->getSQL();die;
            return $qb->getQuery()->getResult();
        }catch (\Exception $exception){
          //  echo $exception->getMessage();die;
            return null;
        }
    }
}
