<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends EntityRepository
{
    public function checkUserWishlistExist($user,$csessId)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb
            ->select('w')
            ->from('AppBundle:Wishlist','w');

        $params = [];

        if($user){
            $qb->where('w.user = :user');
            $params['user'] = $user;
        }else{
            $qb->where('w.sessId = :sessId');
            $params['sessId'] =  $csessId;
        }

        $qb->setParameters($params);

        try{
            return $qb->getQuery()->getSingleResult();
        }catch (\Exception $exception)
        {
            echo $exception->getMessage();
            return null;
        }
    }
}
