services:
     app.form.registration:
         class: AppBundle\Form\RegistrationType
         tags:
             - { name: form.type, alias: register }

     app.email.manager:
         class: AppBundle\Services\EmailManager
         arguments: ["@service_container"]